[package]
name = "holodeck-jarvis"
version = "2.1.1"
release = 1
description = "configuration for raspberry pi 'jarvis'"
requires = [
	"hologram-dummy", # because holo is not packaged yet for arm
	"hologram-base-arch",
	"wpa_supplicant",
	"polkit", # for using poweroff etc. without sudo
]


# user

[[user]]
name    = "laerling"
system  = false
comment = "Benjamin Ludwig"
uid     = 1001
groups  = [ "video", "sudo" ]
home    = "/home/laerling"
shell   = "/bin/bash"

[[directory]]
path = "/home/laerling"
mode = "0700"
owner = 1001 # name doesn't work here
group = 1001 # name doesn't work here


# networking

# WLAN
[[file]]
path = "/etc/wpa_supplicant/wpa_supplicant-wlan0.conf"
content = "# empty" # content must not be emptystring or holo-build will fail
[[symlink]]
# as created by `systemctl enable wpa_supplicant@wlan0`
path = "/etc/systemd/system/multi-user.target.wants/wpa_supplicant@wlan0.service"
target = "/usr/lib/systemd/system/wpa_supplicant@.service"

# dhcp
[[symlink]]
# as created by `systemctl enable dhcpcd`
path = "/etc/systemd/system/multi-user.target.wants/dhcpcd.service"
target = "/usr/lib/systemd/system/dhcpcd.service"

# DNS
[[symlink]]
# as created by `systemctl enable systemd-resolved`
path = "/etc/systemd/system/dbus-org.freedesktop.resolve1.service"
target = "/usr/lib/systemd/system/systemd-resolved.service"
[[symlink]]
# as created by `systemctl enable systemd-resolved`
path = "/etc/systemd/system/multi-user.target.wants/systemd-resolved.service"
target = "/usr/lib/systemd/system/systemd-resolved.service"


# fixes and workarounds

# workaround to keep jarvis from switching to boot screen every now and then
# see https://raspberrypi.stackexchange.com/questions/84240
[[file]]
path = "/etc/modprobe.d/nobootscreen.conf"
mode = "0444"
content = "blacklist vc4" # vc4 seems to be for hardware graphics acceleration

# keep jarvis from logging kaudit messages to the console all the time
# see https://raspberrypi.stackexchange.com/questions/351387
# and https://raspberrypi.stackexchange.com/questions/13019
# The current setting can be read from /proc/sys/kernel/printk
# Before adding printk.conf it was 7 4 1 7
[[file]]
path = "/etc/sysctl.d/printk.conf"
mode = "0444"
content = "kernel.printk = 3 4 1 3"


# other

[[file]]
path = "/home/laerling/.screenrc"
mode = "0444"
content = "vbell off"
