[package]
name = "hologram-desktop-i3"
version = "1.11.1"
release = 1
provides = [ "hologram-desktop" ]
description = "i3 wm and basic desktop utilities. Can be installed alongside any hologram-desktop-*"
requires = [

	# console
	"terminator",
	"xterm", # needed due to /etc/X11/xinit/xinitrc

	# window manager (with status bar and application starter)
	"xorg-server",
	"xorg-xinit",
	"xorg-xrandr", # for configuring peripheral screens etc.
	"i3-wm",
	"i3status",
	"dmenu",

	# fonts
	"gnu-free-fonts", # replaces ttf-freefont
	"adobe-source-code-pro-fonts",

	# standard programs depending on GUI
	"slock",
	"scrot",
	"shotwell", # photo viewer
]


[[file]]
path = "/usr/share/holo/files/02-desktop-i3/etc/i3/config"
mode = "0755"
contentFrom = "files/i3_config"

[[file]]
path = "/etc/X11/xinit/xinitrc.d/hologram-desktop-i3.sh"
mode = "0755"
contentFrom = "files/xinitrc_hologram-desktop-i3.sh"


# own binaries

[[file]]
path = "/usr/local/bin/x"
mode = "0755"
content = "startx"

[[file]]
path = "/usr/local/bin/exiti3"
mode = "0755"
contentFrom = "files/exiti3"

[[file]]
path = "/usr/local/bin/slocksus"
mode = "0755"
contentFrom = "files/slocksus"

[[file]]
path = "/usr/local/bin/slockhib"
mode = "0755"
contentFrom = "files/slockhib"

[[file]]
path = "/usr/local/bin/scrot"
mode = "0755"
contentFrom = "files/scrot"

[[file]]
path = "/usr/local/bin/scrots"
mode = "0755"
contentFrom = "files/scrots"
