[package]
name = "holodeck-trinity"
version = "0.3.2"
release = 1
description = "configuration of server 'trinity'"
requires = [
	"holo-users-groups",

	"hologram-base-arch",
	"openssh",
]


# user

[[group]]
name = "sudo"
system = false

[[user]]
name    = "lsf"
system  = false
uid     = 1000
groups  = [ "sudo" ]
home    = "/home/lsf"
shell   = "/bin/bash"

[[directory]]
path = "/home/lsf"
mode = "0700"
owner = 1000 # name doesn't work here
group = 1000 # name doesn't work here


# DHCP
[[symlink]]
# as created by `systemctl enable dhcpcd`
path = "/etc/systemd/system/multi-user.target.wants/dhcpcd.service"
target = "/usr/lib/systemd/system/dhcpcd.service"


# SSH
# as created by `systemctl enable sshd`
[[symlink]]
path = "/etc/systemd/system/multi-user.target.wants/sshd.service"
target = "/usr/lib/systemd/system/sshd.service"

[[file]]
path = "/usr/share/holo/files/99-trinity/etc/ssh/sshd_config.holoscript"
mode = "0755"
contentFrom = "holoscripts/sshd.sed"
