[package]
name = "hologram-multimedia"
version = "1.5.2"
release = 1
description = "Bundle with video, graphics, audio, communication, and games"
requires = [
	"hologram-audio",
	"hologram-communication",
	"hologram-graphics",
	"hologram-video",
]

[[file]]
path = "/etc/mpv/mpv.conf"
mode = "0644"
content = "audio-display=no"

[[file]]
path = "/usr/bin/decide"
mode = "0755"
contentFrom = "files/decide.sh"
