[package]
name = "hologram-audio"
version = "2.2.2"
release = 1
description = "basic audio infrastructure"
requires = [
	"alsa-utils",
	"pavucontrol",
	"pipewire",

	# E. g. gnome packages depend on pulseaudio and
	# pulseaudio-alsa, so we need to replace them with the
	# pipewire packages that provide those dependencies:
	"pipewire-alsa", # Make sure that pulseaudio-alsa is not installed
	"pipewire-jack", # TODO Why doesn't pipewire-jack replace jack2?
	"pipewire-pulse",

	# auxiliary software:
	"youtube-dl",
	"mp3splt", # contains oggsplt
]

# FIXME: Still loaded
# blacklist HDMI audio module
[[file]]
path = "/etc/modprobe.d/blacklist_hdmi_audio.conf"
mode = "0444"
content = "blacklist snd_hda_codec_hdmi"

# as created by `systemctl --user enable pipewire`
[[symlink]]
path = "/home/laerling/.config/systemd/user/default.target.wants/pipewire.service"
target = "/usr/lib/systemd/user/pipewire.service"
[[symlink]]
path = "/home/laerling/.config/systemd/user/sockets.target.wants/pipewire.socket"
target = "/usr/lib/systemd/user/pipewire.socket"
