[package]
name = "hologram-desktop-cinnamon"
version = "1.6.3"
release = 1
provides = [ "hologram-desktop" ]
description = "cinnamon desktop environment"
requires = [

  # desktop environment
  "cinnamon",

  # display manager
  "hologram-dm",

  # standard programs depending on GUI
  "gnome-calculator",
  "gnome-photos",
  "gnome-terminal", # way better than xterm
  "gnome-screenshot",
  "gnome-system-monitor",
  "scrot",
]


[[file]]
path = "/etc/X11/xinit/xinitrc.d/cinnamon.sh"
mode = "0755"
contentFrom = "files/xinitrc_hologram-desktop-cinnamon.sh"
