[package]
name = "hologram-gui"
version = "3.6.2"
release = 1
description = "Things needed for every desktop"
requires = [

  # graphics drivers have to be included in holodecks

	# desktop environment
	"hologram-desktop",
	# don't depend on hologram-dm, because the desktop environment
	# hologram should know whether it needs a DM. E. g. i3 does
	# not necessarily need one.

	# locales
	"hologram-lang",

	# packages independent of desktop environment
	"scrot",
	# since many desktops can be started with either X or wayland, we might
	# as well depend on both clipboard frontends already
	"xsel",
	"xclip",
	"wl-clipboard",
	"ttf-joypixels",
	"otf-ipafont", # japanese fonts. You think you don't need them? Think again ¯\_(ツ)_/¯
]


[[file]]
path = "/usr/share/holo/files/01-gui/etc/inputrc.holoscript"
mode = "0755"
contentFrom = "files/inputrc.sed"

# remove unnecessary stuff from xinitrc
[[file]]
path = "/usr/share/holo/files/01-gui/etc/X11/xinit/xinitrc.holoscript"
mode = "0755"
contentFrom = "holoscripts/xinitrc.sh"
