#!/usr/bin/bash

cd ~/Downloads || cd "$HOME"
link="$(xsel -b)"
output_pattern='%(title)s %(id)s.%(ext)s'
if (echo "$link"|grep '[&?]list=' > /dev/null); then
	list_name=$(youtube-dl --flat-playlist "$link"|grep "Finished downloading playlist"|sed 's/.*Finished downloading playlist: //')
	echo "Video is part of list: $list_name"
	mkdir "$list_name"
	cd "$list_name"
	output_pattern="%(autonumber)02d $output_pattern"
fi
echo "Downloading to '$PWD'"
echo
youtube-dl "$@" --output "$output_pattern" --no-overwrites --no-cache-dir "$link"
