#!/usr/bin/bash

link="$(xsel -b)"
echo "Clipboard: $link"

# if it's a list, play it whole instead of just one video
if echo "$link"|grep list; then
    link=$(echo "$link"|sed 's/v=[^&]\+&//')
fi

echo "Playing: $link"
mpv "$@" --ytdl-raw-options=no-cache-dir= "$link"
