#!/usr/bin/bash
cat;tail --lines=+4 "$0";exit
# This must stand in the third line of the file. Everything that follows gets written to the destination file verbatim.

####################################
# configuration from hologram-base #
####################################

# overwrite prompt variable
promptcolor="yes"
if [ "$promptcolor" = "yes" ]; then
    PS1="\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ "
else
    PS1="\u@\h:\w\$ "
fi


##aliases

#basic aliases
alias ..='cd ..'
alias cd..='cd ..'
alias ls='ls --color=auto'
alias l='ls -b' # -b = use c-like escape sequences instead of ticks (a\ whitespace instead of 'a whitespace')
alias ll='ls -lF'
alias la='ls -a'
alias lla='ll -a'
alias lld='ll -d'
alias r=rm
alias rf='r -f'
alias cal='cal -m -3' # start week on Monday and display adjecent months
alias s='screen -DRUe^zz'

# system tools and dev
alias grepi='grep -i'
# git (only commands that output stuff, no commands that actually change stuff, that'd be dangerous)
alias gita='git add'             ; alias ga='git add'
alias gitaa='git add -A'         ; alias gaa='git add -A'
alias gitb='git branch -v'       ; alias gb='git branch -v'
alias gitc='git commit'          ; alias gc='git commit' # might shadow /usr/bin/gc from package graphviz
alias gitca='git commit --amend' ; alias gca='git commit --amend'
alias gitcm='git commit -m'      ; alias gcm='git commit -m'
alias gitch='git checkout'       ; alias gch='git checkout'
alias gitco=gitch                ; alias gco=gch
alias gitd='git diff'            ; alias gd='git diff'
alias gitds='git diff --staged'  ; alias gds='git diff --staged'
alias gitl='git log'             ; alias gl='git log'
                                   alias glg='git log --graph --oneline'
                                   alias gla='git log --graph --oneline --all'
alias gitp='git pull'            ; alias gp='git pull'
alias gitst='git stash'          ; alias gst='git stash'
alias gitsta='git stash apply'   ; alias gsta='git stash apply'
alias gitstl='git stash list'    ; alias gstl='git stash list'
alias gitstd='git stash drop'    ; alias gstd='git stash drop'
# don't make an alias for git push because that one should be use with care! I. e. one should have to really want to type it everytime.
# Relying on the login credentials being asked is not enough, since that doesn't happen when pushing with an ssh key.
# Besides, only commands that output stuff, no commands that actually change stuff, as already stated above
alias gitr='git remote -v'       ; alias gr='git remote -v'
alias gits='git status'          ; alias gs='git status' # might shadow ghostscript

# editors
alias eq='emacs -q'
alias e=emacs

# Multimedia # TODO move into hologram-multimedia
alias loop='mpv --loop-playlist'
alias shuffle='loop --shuffle '
alias play='shuffle --no-video'
alias music='play ~/Music'

#custom variables
export EDITOR='emacs -nw'
export VISUAL=vim

## red and green highlighting
#export LESS_TERMCAP_mb=$'\e[1;32m'
#export LESS_TERMCAP_md=$'\e[1;32m'
#export LESS_TERMCAP_me=$'\e[0m'
#export LESS_TERMCAP_se=$'\e[0m'
#export LESS_TERMCAP_so=$'\e[01;33m'
#export LESS_TERMCAP_ue=$'\e[0m'
#export LESS_TERMCAP_us=$'\e[1;4;31m'

# green and blue highlighting
export LESS_TERMCAP_mb=$'\E[1;31m'     # begin bold
export LESS_TERMCAP_md=$'\E[1;36m'     # begin blink
export LESS_TERMCAP_me=$'\E[0m'        # reset bold/blink
export LESS_TERMCAP_so=$'\E[01;44;33m' # begin reverse video
export LESS_TERMCAP_se=$'\E[0m'        # reset reverse video
export LESS_TERMCAP_us=$'\E[1;32m'     # begin underline
export LESS_TERMCAP_ue=$'\E[0m'        # reset underline
export GROFF_NO_SGR=1                  # for konsole and gnome-terminal
