#!/usr/bin/bash
cat;tail --lines=+4 "$0";exit
# This must stand in the third line of the file. Everything that follows gets written to the destination file verbatim.

#########################################
# configuration from hologram-base-arch #
#########################################

# only update system if screen is running
if (ps -e | grep '\<screen\>' >/dev/null); then

# upgrade system
upgradefile=~/.last_upgrade
touch "$upgradefile" # just so that it exists
if [ "$(cat "$upgradefile")" != $(date -I) ]; then
    read -p "Upgrade system (y/N)" upgrade
    if [ "$upgrade" = y ]; then
        date -I > "$upgradefile"
        if hash yaourt 2>/dev/null; then
            yaourt -Syu || rm "$upgradefile"
        else
            sudo pacman -Syu || rm "$upgradefile"
        fi
    fi
fi

else

ps -e | grep 'Xorg\|sway\|gnome-sess' && screen -DR

fi
